// FIFA World Cup 2026 App Data
// Tournament dates: June 11 – July 19, 2026
// App "current date": June 14, 2026

export const TOURNAMENT = {
  year: 2026,
  hosts: ['США', 'Канада', 'Мексика'],
  hostFlags: ['🇺🇸', '🇨🇦', '🇲🇽'],
  teams: 48,
  groups: 12,
  startDate: '11 июня 2026',
  finalDate: '19 июля 2026',
  motto: 'We Are 16',
};

export const TEAMS = {
  USA: { name: 'США', flag: '🇺🇸', group: 'A' },
  COL: { name: 'Колумбия', flag: '🇨🇴', group: 'A' },
  MAR: { name: 'Марокко', flag: '🇲🇦', group: 'A' },
  NZL: { name: 'Н. Зеландия', flag: '🇳🇿', group: 'A' },
  ARG: { name: 'Аргентина', flag: '🇦🇷', group: 'B' },
  GER: { name: 'Германия', flag: '🇩🇪', group: 'B' },
  CIV: { name: 'Кот-д\'Ивуар', flag: '🇨🇮', group: 'B' },
  JPN: { name: 'Япония', flag: '🇯🇵', group: 'B' },
  BRA: { name: 'Бразилия', flag: '🇧🇷', group: 'C' },
  FRA: { name: 'Франция', flag: '🇫🇷', group: 'C' },
  CAN: { name: 'Канада', flag: '🇨🇦', group: 'C' },
  GHA: { name: 'Гана', flag: '🇬🇭', group: 'C' },
  ENG: { name: 'Англия', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'D' },
  ESP: { name: 'Испания', flag: '🇪🇸', group: 'D' },
  KSA: { name: 'Саудовская Аравия', flag: '🇸🇦', group: 'D' },
  ECU: { name: 'Эквадор', flag: '🇪🇨', group: 'D' },
  NED: { name: 'Нидерланды', flag: '🇳🇱', group: 'E' },
  POR: { name: 'Португалия', flag: '🇵🇹', group: 'E' },
  NGA: { name: 'Нигерия', flag: '🇳🇬', group: 'E' },
  AUS: { name: 'Австралия', flag: '🇦🇺', group: 'E' },
  MEX: { name: 'Мексика', flag: '🇲🇽', group: 'F' },
  BEL: { name: 'Бельгия', flag: '🇧🇪', group: 'F' },
  SRB: { name: 'Сербия', flag: '🇷🇸', group: 'F' },
  TUN: { name: 'Тунис', flag: '🇹🇳', group: 'F' },
  URU: { name: 'Уругвай', flag: '🇺🇾', group: 'G' },
  SUI: { name: 'Швейцария', flag: '🇨🇭', group: 'G' },
  KOR: { name: 'Южная Корея', flag: '🇰🇷', group: 'G' },
  CMR: { name: 'Камерун', flag: '🇨🇲', group: 'G' },
  CRO: { name: 'Хорватия', flag: '🇭🇷', group: 'H' },
  TUR: { name: 'Турция', flag: '🇹🇷', group: 'H' },
  ALG: { name: 'Алжир', flag: '🇩🇿', group: 'H' },
  GUA: { name: 'Гватемала', flag: '🇬🇹', group: 'H' },
  DEN: { name: 'Дания', flag: '🇩🇰', group: 'I' },
  CHI: { name: 'Чили', flag: '🇨🇱', group: 'I' },
  IRQ: { name: 'Ирак', flag: '🇮🇶', group: 'I' },
  IDN: { name: 'Индонезия', flag: '🇮🇩', group: 'I' },
  POL: { name: 'Польша', flag: '🇵🇱', group: 'J' },
  SEN: { name: 'Сенегал', flag: '🇸🇳', group: 'J' },
  ITA: { name: 'Италия', flag: '🇮🇹', group: 'J' },
  JOR: { name: 'Иордания', flag: '🇯🇴', group: 'J' },
  UKR: { name: 'Украина', flag: '🇺🇦', group: 'K' },
  PAR: { name: 'Парагвай', flag: '🇵🇾', group: 'K' },
  IRN: { name: 'Иран', flag: '🇮🇷', group: 'K' },
  HON: { name: 'Гондурас', flag: '🇭🇳', group: 'K' },
  SCO: { name: 'Шотландия', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'L' },
  VEN: { name: 'Венесуэла', flag: '🇻🇪', group: 'L' },
  BOL: { name: 'Боливия', flag: '🇧🇴', group: 'L' },
  QAT: { name: 'Катар', flag: '🇶🇦', group: 'L' },
};

// status: 'live' | 'finished' | 'upcoming'
export const MATCHES = [
  // LIVE (June 14, 2026)
  {
    id: 'm10',
    group: 'C',
    date: '14 июня',
    time: '67\'',
    status: 'live',
    home: 'BRA',
    away: 'CAN',
    scoreHome: 2,
    scoreAway: 1,
    venue: 'SoFi Stadium, Inglewood',
    goals: [
      { team: 'BRA', player: 'Виниcius Jr.', minute: 23 },
      { team: 'BRA', player: 'Родриго', minute: 41 },
      { team: 'CAN', player: 'Дэвид', minute: 58 },
    ],
  },
  {
    id: 'm11',
    group: 'D',
    date: '14 июня',
    time: '43\'',
    status: 'live',
    home: 'ENG',
    away: 'ECU',
    scoreHome: 1,
    scoreAway: 0,
    venue: 'MetLife Stadium, Нью-Йорк',
    goals: [
      { team: 'ENG', player: 'Беллингем', minute: 28 },
    ],
  },
  {
    id: 'm12',
    group: 'E',
    date: '14 июня',
    time: '12\'',
    status: 'live',
    home: 'NED',
    away: 'AUS',
    scoreHome: 0,
    scoreAway: 0,
    venue: 'AT&T Stadium, Даллас',
    goals: [],
  },

  // FINISHED (June 11-13)
  {
    id: 'm01',
    group: 'A',
    date: '11 июня',
    time: '90\'',
    status: 'finished',
    home: 'USA',
    away: 'COL',
    scoreHome: 1,
    scoreAway: 2,
    venue: 'Rose Bowl, Лос-Анджелес',
    goals: [
      { team: 'USA', player: 'Пулишич', minute: 34 },
      { team: 'COL', player: 'Диас Л.', minute: 55 },
      { team: 'COL', player: 'Фалькао', minute: 78 },
    ],
  },
  {
    id: 'm02',
    group: 'B',
    date: '11 июня',
    time: '90\'',
    status: 'finished',
    home: 'ARG',
    away: 'CIV',
    scoreHome: 2,
    scoreAway: 0,
    venue: 'Estadio Azteca, Мехико',
    goals: [
      { team: 'ARG', player: 'Месси', minute: 22 },
      { team: 'ARG', player: 'Альварес', minute: 67 },
    ],
  },
  {
    id: 'm03',
    group: 'C',
    date: '11 июня',
    time: '90\'',
    status: 'finished',
    home: 'FRA',
    away: 'GHA',
    scoreHome: 3,
    scoreAway: 0,
    venue: 'Lumen Field, Сиэтл',
    goals: [
      { team: 'FRA', player: 'Мбаппе', minute: 8 },
      { team: 'FRA', player: 'Гризманн', minute: 44 },
      { team: 'FRA', player: 'Мбаппе', minute: 71 },
    ],
  },
  {
    id: 'm04',
    group: 'D',
    date: '12 июня',
    time: '90\'',
    status: 'finished',
    home: 'ESP',
    away: 'KSA',
    scoreHome: 2,
    scoreAway: 1,
    venue: 'Hard Rock Stadium, Майами',
    goals: [
      { team: 'ESP', player: 'Ямаль', minute: 15 },
      { team: 'KSA', player: 'Аль-Шехри', minute: 38 },
      { team: 'ESP', player: 'Мората', minute: 82 },
    ],
  },
  {
    id: 'm05',
    group: 'B',
    date: '12 июня',
    time: '90\'',
    status: 'finished',
    home: 'GER',
    away: 'JPN',
    scoreHome: 1,
    scoreAway: 1,
    venue: 'Arrowhead Stadium, Канзас',
    goals: [
      { team: 'GER', player: 'Мусиала', minute: 29 },
      { team: 'JPN', player: 'Дзан', minute: 85 },
    ],
  },
  {
    id: 'm06',
    group: 'E',
    date: '12 июня',
    time: '90\'',
    status: 'finished',
    home: 'POR',
    away: 'NGA',
    scoreHome: 1,
    scoreAway: 0,
    venue: 'Empower Field, Денвер',
    goals: [
      { team: 'POR', player: 'Роналду', minute: 61 },
    ],
  },
  {
    id: 'm07',
    group: 'F',
    date: '13 июня',
    time: '90\'',
    status: 'finished',
    home: 'BEL',
    away: 'TUN',
    scoreHome: 2,
    scoreAway: 0,
    venue: 'Lincoln Financial, Филадельфия',
    goals: [
      { team: 'BEL', player: 'Де Брёйне', minute: 36 },
      { team: 'BEL', player: 'Лукаку', minute: 74 },
    ],
  },
  {
    id: 'm08',
    group: 'G',
    date: '13 июня',
    time: '90\'',
    status: 'finished',
    home: 'URU',
    away: 'CMR',
    scoreHome: 1,
    scoreAway: 0,
    venue: 'Gillette Stadium, Бостон',
    goals: [
      { team: 'URU', player: 'Нуньес', minute: 52 },
    ],
  },
  {
    id: 'm09',
    group: 'A',
    date: '13 июня',
    time: '90\'',
    status: 'finished',
    home: 'MAR',
    away: 'NZL',
    scoreHome: 3,
    scoreAway: 0,
    venue: 'Allegiant Stadium, Лас-Вегас',
    goals: [
      { team: 'MAR', player: 'Зиеш', minute: 17 },
      { team: 'MAR', player: 'Эн-Несири', minute: 44 },
      { team: 'MAR', player: 'Зиеш', minute: 88 },
    ],
  },

  // UPCOMING
  {
    id: 'm13',
    group: 'F',
    date: '14 июня',
    time: '21:00',
    status: 'upcoming',
    home: 'MEX',
    away: 'SRB',
    venue: 'Estadio BBVA, Монтеррей',
    goals: [],
  },
  {
    id: 'm14',
    group: 'G',
    date: '15 июня',
    time: '18:00',
    status: 'upcoming',
    home: 'SUI',
    away: 'KOR',
    venue: 'Levi\'s Stadium, Санта-Клара',
    goals: [],
  },
  {
    id: 'm15',
    group: 'H',
    date: '15 июня',
    time: '21:00',
    status: 'upcoming',
    home: 'CRO',
    away: 'TUR',
    venue: 'NRG Stadium, Хьюстон',
    goals: [],
  },
  {
    id: 'm16',
    group: 'I',
    date: '16 июня',
    time: '18:00',
    status: 'upcoming',
    home: 'DEN',
    away: 'CHI',
    venue: 'Mercedes-Benz Stadium, Атланта',
    goals: [],
  },
  {
    id: 'm17',
    group: 'J',
    date: '16 июня',
    time: '21:00',
    status: 'upcoming',
    home: 'ITA',
    away: 'SEN',
    venue: 'Hard Rock Stadium, Майами',
    goals: [],
  },
  {
    id: 'm18',
    group: 'K',
    date: '17 июня',
    time: '18:00',
    status: 'upcoming',
    home: 'UKR',
    away: 'PAR',
    venue: 'BC Place, Ванкувер',
    goals: [],
  },
  {
    id: 'm19',
    group: 'L',
    date: '17 июня',
    time: '21:00',
    status: 'upcoming',
    home: 'SCO',
    away: 'VEN',
    venue: 'Estadio Akron, Гвадалахара',
    goals: [],
  },
];

export const TOP_SCORERS = [
  { rank: 1, name: 'Килиан Мбаппе', team: 'FRA', club: 'Real Madrid', goals: 2, assists: 1, matches: 1, avatar: '⚡' },
  { rank: 2, name: 'Хаким Зиеш', team: 'MAR', club: 'Al-Qadisiyah', goals: 2, assists: 0, matches: 1, avatar: '🔮' },
  { rank: 3, name: 'Лионель Месси', team: 'ARG', club: 'Inter Miami', goals: 1, assists: 0, matches: 1, avatar: '🐐' },
  { rank: 4, name: 'Виниций Жуниор', team: 'BRA', club: 'Real Madrid', goals: 1, assists: 0, matches: 2, avatar: '🔥' },
  { rank: 5, name: 'Антуан Гризманн', team: 'FRA', club: 'Atletico Madrid', goals: 1, assists: 0, matches: 1, avatar: '🎯' },
  { rank: 6, name: 'Хулиан Альварес', team: 'ARG', club: 'Man City', goals: 1, assists: 0, matches: 1, avatar: '🐺' },
  { rank: 7, name: 'Ламин Ямаль', team: 'ESP', club: 'Barcelona', goals: 1, assists: 0, matches: 1, avatar: '⭐' },
  { rank: 8, name: 'Криштиану Роналду', team: 'POR', club: 'Al-Nassr', goals: 1, assists: 0, matches: 1, avatar: '🦁' },
  { rank: 9, name: 'Луис Диас', team: 'COL', club: 'Liverpool', goals: 1, assists: 0, matches: 1, avatar: '🐆' },
  { rank: 10, name: 'Кевин Де Брёйне', team: 'BEL', club: 'Man City', goals: 1, assists: 0, matches: 1, avatar: '👑' },
  { rank: 11, name: 'Ромелу Лукаку', team: 'BEL', club: 'Napoli', goals: 1, assists: 0, matches: 1, avatar: '🏋️' },
  { rank: 12, name: 'Родриго', team: 'BRA', club: 'Real Madrid', goals: 1, assists: 0, matches: 2, avatar: '⚡' },
  { rank: 13, name: 'Кристиан Пулишич', team: 'USA', club: 'AC Milan', goals: 1, assists: 0, matches: 1, avatar: '🌟' },
  { rank: 14, name: 'Дарвин Нуньес', team: 'URU', club: 'Liverpool', goals: 1, assists: 0, matches: 1, avatar: '🐂' },
  { rank: 15, name: 'Флавиан Эн-Несири', team: 'MAR', club: 'Fenerbahce', goals: 1, assists: 0, matches: 1, avatar: '🦅' },
];

export const GOALKEEPERS = [
  {
    rank: 1,
    name: 'Эмильяно Мартинес',
    team: 'ARG',
    club: 'Aston Villa',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 3,
    rating: 9.2,
  },
  {
    rank: 2,
    name: 'Яссин Буну',
    team: 'MAR',
    club: 'Al-Hilal',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 2,
    rating: 8.8,
  },
  {
    rank: 3,
    name: 'Андре Оана',
    team: 'FRA',
    club: 'PSG',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 1,
    rating: 8.5,
  },
  {
    rank: 4,
    name: 'Тибо Куртуа',
    team: 'BEL',
    club: 'Real Madrid',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 2,
    rating: 8.7,
  },
  {
    rank: 5,
    name: 'Диого Кошта',
    team: 'POR',
    club: 'Porto',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 4,
    rating: 8.9,
  },
  {
    rank: 6,
    name: 'Фернандо Муслера',
    team: 'URU',
    club: 'Galatasaray',
    matches: 1,
    cleanSheets: 1,
    minutesWithoutGoal: 90,
    saves: 2,
    rating: 8.4,
  },
  {
    rank: 7,
    name: 'Матс Хюмелс (вр.)',
    team: 'GER',
    club: 'Bayern',
    matches: 1,
    cleanSheets: 0,
    minutesWithoutGoal: 84,
    saves: 3,
    rating: 7.8,
  },
  {
    rank: 8,
    name: 'Алехандро Маньян',
    team: 'ESP',
    club: 'Barcelona',
    matches: 1,
    cleanSheets: 0,
    minutesWithoutGoal: 37,
    saves: 2,
    rating: 7.5,
  },
  {
    rank: 9,
    name: 'Мэт Тёрнер',
    team: 'USA',
    club: 'Crystal Palace',
    matches: 1,
    cleanSheets: 0,
    minutesWithoutGoal: 33,
    saves: 3,
    rating: 7.2,
  },
  {
    rank: 10,
    name: 'Эдерсон',
    team: 'BRA',
    club: 'Man City',
    matches: 2,
    cleanSheets: 0,
    minutesWithoutGoal: 57,
    saves: 4,
    rating: 7.9,
  },
];

export const GROUPS = {
  A: {
    name: 'Группа A',
    teams: [
      { code: 'MAR', p: 1, w: 1, d: 0, l: 0, gf: 3, ga: 0, gd: 3, pts: 3 },
      { code: 'COL', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 1, gd: 1, pts: 3 },
      { code: 'USA', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 2, gd: -1, pts: 0 },
      { code: 'NZL', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 3, gd: -3, pts: 0 },
    ],
  },
  B: {
    name: 'Группа B',
    teams: [
      { code: 'ARG', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 0, gd: 2, pts: 3 },
      { code: 'GER', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { code: 'JPN', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { code: 'CIV', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 2, gd: -2, pts: 0 },
    ],
  },
  C: {
    name: 'Группа C',
    teams: [
      { code: 'FRA', p: 1, w: 1, d: 0, l: 0, gf: 3, ga: 0, gd: 3, pts: 3 },
      { code: 'BRA', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 1, gd: 1, pts: 3 },
      { code: 'CAN', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 2, gd: -1, pts: 0 },
      { code: 'GHA', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 3, gd: -3, pts: 0 },
    ],
  },
  D: {
    name: 'Группа D',
    teams: [
      { code: 'ESP', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 1, gd: 1, pts: 3 },
      { code: 'ENG', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { code: 'KSA', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 2, gd: -1, pts: 0 },
      { code: 'ECU', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
    ],
  },
  E: {
    name: 'Группа E',
    teams: [
      { code: 'POR', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { code: 'NED', p: 1, w: 0, d: 1, l: 0, gf: 0, ga: 0, gd: 0, pts: 1 },
      { code: 'AUS', p: 1, w: 0, d: 1, l: 0, gf: 0, ga: 0, gd: 0, pts: 1 },
      { code: 'NGA', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
    ],
  },
  F: {
    name: 'Группа F',
    teams: [
      { code: 'BEL', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 0, gd: 2, pts: 3 },
      { code: 'MEX', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'SRB', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'TUN', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 2, gd: -2, pts: 0 },
    ],
  },
  G: {
    name: 'Группа G',
    teams: [
      { code: 'URU', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { code: 'SUI', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'KOR', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'CMR', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
    ],
  },
  H: {
    name: 'Группа H',
    teams: [
      { code: 'CRO', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'TUR', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'ALG', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'GUA', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
    ],
  },
  I: {
    name: 'Группа I',
    teams: [
      { code: 'DEN', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'CHI', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'IRQ', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'IDN', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
    ],
  },
  J: {
    name: 'Группа J',
    teams: [
      { code: 'ITA', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'SEN', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'POL', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'JOR', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
    ],
  },
  K: {
    name: 'Группа K',
    teams: [
      { code: 'UKR', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'PAR', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'IRN', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'HON', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
    ],
  },
  L: {
    name: 'Группа L',
    teams: [
      { code: 'SCO', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'VEN', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'BOL', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
      { code: 'QAT', p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 },
    ],
  },
};

export const HISTORY = [
  {
    year: 1930, host: 'Уругвай', flag: '🇺🇾', winner: 'Уругвай', winnerFlag: '🇺🇾',
    runnerUp: 'Аргентина', runnerUpFlag: '🇦🇷', score: '4:2',
    topScorer: 'Г. Стабиле (Аргентина) — 8 голов',
    teams: 13, goals: 70, attendance: '434 000',
    fact: 'Первый в истории чемпионат мира. Уругвай победил у себя дома, Аргентина стала финалистом дебютного турнира.',
  },
  {
    year: 1934, host: 'Италия', flag: '🇮🇹', winner: 'Италия', winnerFlag: '🇮🇹',
    runnerUp: 'Чехословакия', runnerUpFlag: '🇨🇿', score: '2:1 д.в.',
    topScorer: 'О. Шаффер (Австрия/Венгрия) — 4 гола',
    teams: 16, goals: 70, attendance: '363 000',
    fact: 'Первый турнир с квалификационными матчами. Уругвай отказался участвовать в знак протеста.',
  },
  {
    year: 1938, host: 'Франция', flag: '🇫🇷', winner: 'Италия', winnerFlag: '🇮🇹',
    runnerUp: 'Венгрия', runnerUpFlag: '🇭🇺', score: '4:2',
    topScorer: 'Л. Сентотти (Бразилия) — 7 голов',
    teams: 15, goals: 84, attendance: '374 835',
    fact: 'Италия стала первой командой, защитившей титул чемпиона мира. Бразилец Леонидас был звездой турнира.',
  },
  {
    year: 1950, host: 'Бразилия', flag: '🇧🇷', winner: 'Уругвай', winnerFlag: '🇺🇾',
    runnerUp: 'Бразилия', runnerUpFlag: '🇧🇷', score: '2:1',
    topScorer: 'А. Адемир (Бразилия) — 9 голов',
    teams: 13, goals: 88, attendance: '1 337 000',
    fact: '«Мараканасо» — шокирующая победа Уругвая над Бразилией на Маракане перед 200 000 болельщиков.',
  },
  {
    year: 1954, host: 'Швейцария', flag: '🇨🇭', winner: 'ФРГ', winnerFlag: '🇩🇪',
    runnerUp: 'Венгрия', runnerUpFlag: '🇭🇺', score: '3:2',
    topScorer: 'С. Кочиш (Венгрия) — 11 голов',
    teams: 16, goals: 140, attendance: '943 000',
    fact: '«Чудо в Берне». Германия победила непобедимых венгров (Пушкаш, Хидегкути) в финале — 3:2.',
  },
  {
    year: 1958, host: 'Швеция', flag: '🇸🇪', winner: 'Бразилия', winnerFlag: '🇧🇷',
    runnerUp: 'Швеция', runnerUpFlag: '🇸🇪', score: '5:2',
    topScorer: 'Ж. Фонтен (Франция) — 13 голов',
    teams: 16, goals: 126, attendance: '819 810',
    fact: '17-летний Пеле забил 6 голов. Рекорд Фонтена (13 голов) не побит по сей день.',
  },
  {
    year: 1962, host: 'Чили', flag: '🇨🇱', winner: 'Бразилия', winnerFlag: '🇧🇷',
    runnerUp: 'Чехословакия', runnerUpFlag: '🇨🇿', score: '3:1',
    topScorer: 'Г. Альберт, Д. Жанев и др. — 4 гола',
    teams: 16, goals: 89, attendance: '893 172',
    fact: 'Бразилия выиграла без травмированного Пеле. Гарринча стал главной звездой турнира.',
  },
  {
    year: 1966, host: 'Англия', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', winner: 'Англия', winnerFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    runnerUp: 'ФРГ', runnerUpFlag: '🇩🇪', score: '4:2 д.в.',
    topScorer: 'Э. Хёрст (Англия) — 4 гола',
    teams: 16, goals: 89, attendance: '1 614 677',
    fact: 'Знаменитый «гол Хёрста» в финале — до сих пор споры, пересек ли мяч линию.',
  },
  {
    year: 1970, host: 'Мексика', flag: '🇲🇽', winner: 'Бразилия', winnerFlag: '🇧🇷',
    runnerUp: 'Италия', runnerUpFlag: '🇮🇹', score: '4:1',
    topScorer: 'Г. Мюллер (ФРГ) — 10 голов',
    teams: 16, goals: 95, attendance: '1 673 975',
    fact: 'Бразилия — первая 3-кратная чемпионка. Пеле, Жаирзиньо, Ривелино — лучший состав в истории.',
  },
  {
    year: 1974, host: 'ФРГ', flag: '🇩🇪', winner: 'ФРГ', winnerFlag: '🇩🇪',
    runnerUp: 'Нидерланды', runnerUpFlag: '🇳🇱', score: '2:1',
    topScorer: 'Г. Лато (Польша) — 7 голов',
    teams: 16, goals: 97, attendance: '1 865 753',
    fact: 'Кройфф и «Тотальный футбол» — Нидерланды стали фаворитами. Германия Бекенбауэра выиграла финал.',
  },
  {
    year: 1978, host: 'Аргентина', flag: '🇦🇷', winner: 'Аргентина', winnerFlag: '🇦🇷',
    runnerUp: 'Нидерланды', runnerUpFlag: '🇳🇱', score: '3:1 д.в.',
    topScorer: 'М. Кемпес (Аргентина) — 6 голов',
    teams: 16, goals: 102, attendance: '1 610 215',
    fact: 'Марио Кемпес провёл блестящий финал. Скандал с матчем Аргентина–Перу 6:0.',
  },
  {
    year: 1982, host: 'Испания', flag: '🇪🇸', winner: 'Италия', winnerFlag: '🇮🇹',
    runnerUp: 'ФРГ', runnerUpFlag: '🇩🇪', score: '3:1',
    topScorer: 'П. Росси (Италия) — 6 голов',
    teams: 24, goals: 146, attendance: '2 109 723',
    fact: 'Паоло Росси — лучший бомбардир и игрок турнира. Бразилия образца 1982 считается «самой красивой потерей».',
  },
  {
    year: 1986, host: 'Мексика', flag: '🇲🇽', winner: 'Аргентина', winnerFlag: '🇦🇷',
    runnerUp: 'ФРГ', runnerUpFlag: '🇩🇪', score: '3:2',
    topScorer: 'Г. Линекер (Англия) — 6 голов',
    teams: 24, goals: 132, attendance: '2 394 031',
    fact: '«Рука Бога» и «Гол века» — два гола Марадоны против Англии в четвертьфинале.',
  },
  {
    year: 1990, host: 'Италия', flag: '🇮🇹', winner: 'ФРГ', winnerFlag: '🇩🇪',
    runnerUp: 'Аргентина', runnerUpFlag: '🇦🇷', score: '1:0',
    topScorer: 'С. Скиллачи (Италия) — 6 голов',
    teams: 24, goals: 115, attendance: '2 516 215',
    fact: 'Самый низкий голевой показатель. Слёзы Скиллачи и Гасконя. Финал выиграл пенальти Брема.',
  },
  {
    year: 1994, host: 'США', flag: '🇺🇸', winner: 'Бразилия', winnerFlag: '🇧🇷',
    runnerUp: 'Италия', runnerUpFlag: '🇮🇹', score: '0:0 (3:2 пен.)',
    topScorer: 'О. Салас (Болгария/Болгария), Х.Л. Клинсманн и др. — 6 голов',
    teams: 24, goals: 141, attendance: '3 587 538',
    fact: 'Рекорд посещаемости всех времён. Роберто Баджо промахнулся с пенальти в финале — слёзы Ponytail.',
  },
  {
    year: 1998, host: 'Франция', flag: '🇫🇷', winner: 'Франция', winnerFlag: '🇫🇷',
    runnerUp: 'Бразилия', runnerUpFlag: '🇧🇷', score: '3:0',
    topScorer: 'Д. Суккер (Хорватия) — 6 голов',
    teams: 32, goals: 171, attendance: '2 785 100',
    fact: 'Зинедин Зидан дублем в финале. Странный Роналду перед финалом. Дебют хорватов в 1/2 финала.',
  },
  {
    year: 2002, host: 'Ю.Корея / Япония', flag: '🇰🇷🇯🇵', winner: 'Бразилия', winnerFlag: '🇧🇷',
    runnerUp: 'Германия', runnerUpFlag: '🇩🇪', score: '2:0',
    topScorer: 'Роналдо (Бразилия) — 8 голов',
    teams: 32, goals: 161, attendance: '2 705 197',
    fact: 'R9 Роналдо — 8 голов и золото. Сенсации: Корея в топ-4, вылет Аргентины и Франции в группе.',
  },
  {
    year: 2006, host: 'Германия', flag: '🇩🇪', winner: 'Италия', winnerFlag: '🇮🇹',
    runnerUp: 'Франция', runnerUpFlag: '🇫🇷', score: '1:1 (5:3 пен.)',
    topScorer: 'М. Клозе (Германия) — 5 голов',
    teams: 32, goals: 147, attendance: '3 359 439',
    fact: 'Знаменитый удар головой Зидана Матерацци и удаление в финале. Итальянцы — чемпионы.',
  },
  {
    year: 2010, host: 'ЮАР', flag: '🇿🇦', winner: 'Испания', winnerFlag: '🇪🇸',
    runnerUp: 'Нидерланды', runnerUpFlag: '🇳🇱', score: '1:0 д.в.',
    topScorer: 'Т. Мюллер, Д. Форлан и др. — 5 голов',
    teams: 32, goals: 145, attendance: '3 178 856',
    fact: 'Первый ЧМ в Африке. Осьминог Пауль предсказал все матчи. Гол Иньесты в д.в.',
  },
  {
    year: 2014, host: 'Бразилия', flag: '🇧🇷', winner: 'Германия', winnerFlag: '🇩🇪',
    runnerUp: 'Аргентина', runnerUpFlag: '🇦🇷', score: '1:0 д.в.',
    topScorer: 'Х. Родригес (Колумбия) — 6 голов',
    teams: 32, goals: 171, attendance: '3 429 873',
    fact: '«Минейразо» 7:1 против Бразилии — самое большое унижение в истории. Гётце — чемпион.',
  },
  {
    year: 2018, host: 'Россия', flag: '🇷🇺', winner: 'Франция', winnerFlag: '🇫🇷',
    runnerUp: 'Хорватия', runnerUpFlag: '🇭🇷', score: '4:2',
    topScorer: 'Х. Кейн (Англия) — 6 голов',
    teams: 32, goals: 169, attendance: '3 031 768',
    fact: 'Хорватия впервые в финале! Мбаппе — MVP. 2 автогола в одном финале — рекорд.',
  },
  {
    year: 2022, host: 'Катар', flag: '🇶🇦', winner: 'Аргентина', winnerFlag: '🇦🇷',
    runnerUp: 'Франция', runnerUpFlag: '🇫🇷', score: '3:3 (4:2 пен.)',
    topScorer: 'К. Мбаппе (Франция) — 8 голов',
    teams: 32, goals: 172, attendance: '3 404 252',
    fact: 'ЛУЧШИЙ ФИНАЛ ВСЕХ ВРЕМЁН! Месси получил Кубок — мечта осуществилась. Мбаппе — хет-трик в финале.',
  },
];

export const NEWS = [
  {
    id: 1,
    category: 'ИНСАЙД',
    categoryColor: '#E63946',
    title: 'Месси: «Это мой последний Чемпионат мира»',
    summary: 'Капитан сборной Аргентины заявил, что намерен завершить карьеру в сборной после 2026 года. «Хочу выиграть ещё раз для моего народа», — сказал 38-летняя легенда.',
    time: '2 ч назад',
    emoji: '🐐',
    views: '2.4М',
    hot: true,
  },
  {
    id: 2,
    category: 'ТРАВМА',
    categoryColor: '#F97316',
    title: 'Беллингем под вопросом перед 1/8 финала',
    summary: 'Полузащитник Англии получил мышечный ушиб в матче с Эквадором. Медицинский штаб оценивает его состояние. Тренер Саутгейт настроен оптимистично.',
    time: '4 ч назад',
    emoji: '🚑',
    views: '890К',
    hot: false,
  },
  {
    id: 3,
    category: 'АНАЛИЗ',
    categoryColor: '#00D4FF',
    title: 'Почему схема 4-3-3 доминирует на ЧМ-2026',
    summary: '7 из 8 матчей сыграно в этой расстановке. Разбираем тактику Дешама, Скалони и Гвардиолы — в чём секрет успеха тройки форвардов в современном футболе.',
    time: '6 ч назад',
    emoji: '📊',
    views: '1.1М',
    hot: false,
  },
  {
    id: 4,
    category: 'РЕКОРД',
    categoryColor: '#FFD700',
    title: 'Мбаппе — 3-й бомбардир Франции на ЧМ',
    summary: 'Дубль в матче с Ганой вывел Кылиана на 3-е место в списке лучших бомбардиров сборной Франции на чемпионатах мира. Лидер — Жюст Фонтен с 13 голами.',
    time: '12 ч назад',
    emoji: '⚡',
    views: '3.2М',
    hot: true,
  },
  {
    id: 5,
    category: 'ИНСАЙД',
    categoryColor: '#E63946',
    title: 'Роналду поссорился с тренером Мартинесом',
    summary: 'По данным источников в стане сборной Португалии, CR7 недоволен тем, что его выпускают лишь на 60 минут. Тренер настаивает на ротации состава.',
    time: '1 д назад',
    emoji: '🦁',
    views: '4.8М',
    hot: true,
  },
  {
    id: 6,
    category: 'ИСТОРИЯ',
    categoryColor: '#7B5EA7',
    title: '«Мараканасо»-2026: повторит ли Бразилия трагедию 1950?',
    summary: 'Бразилия снова играет в США — стране, ставшей хозяйкой её провального ЧМ-1994. Дежавю или новая эра? Специальный репортаж нашей редакции.',
    time: '1 д назад',
    emoji: '🇧🇷',
    views: '560К',
    hot: false,
  },
  {
    id: 7,
    category: 'ТЕХНИКА',
    categoryColor: '#22c55e',
    title: 'VAR 4.0: как ИИ меняет судейство на ЧМ-2026',
    summary: 'FIFA внедрила систему автоматического определения офсайда с погрешностью 2 мм. Уже 3 решения были оспорены и изменены за первые дни турнира.',
    time: '2 д назад',
    emoji: '🤖',
    views: '780К',
    hot: false,
  },
  {
    id: 8,
    category: 'ИНСАЙД',
    categoryColor: '#E63946',
    title: 'Неймар снова рвётся на поле — но в сборной Бразилии',
    summary: 'Многократно травмированный форвард наблюдает за турниром с трибуны и публично заявил о желании «помочь команде». Тито отметает любые разговоры о возвращении.',
    time: '2 д назад',
    emoji: '🎭',
    views: '2.9М',
    hot: true,
  },
];

export const TICKER_ITEMS = [
  '⚽ LIVE: Бразилия 2–1 Канада (67\')',
  '⚽ LIVE: Англия 1–0 Эквадор (43\')',
  '⚽ LIVE: Нидерланды 0–0 Австралия (12\')',
  '🏆 Итого голов на турнире: 29',
  '📊 Матчей сыграно: 9 из 104',
  '⭐ Лучший игрок дня: Килиан Мбаппе',
  '🔥 Мбаппе 2026: 2 гола в 1 матче',
];
